from typing import Dict
import pandas


def create_dataframe_gold_c08_instrument_index_sql_01_00(
        s_instrument_index: pandas.DataFrame) \
        -> pandas.DataFrame:
    column_rename_dict = \
        {
            'Ex_ID': 'Ex-ID',
            'Certificate': 'Certificate',
            'Parts_Code': 'Parts Code',
            'Facility_Block_Default': 'Facility Block Default',
            'Location_Block_Default': 'Location Block Def.',
            'CS_description': 'description',
            'Model': 'Model',
            'Suppl_Char_for_Instr_Elements_1': 'Suppl. Char. for Instr. Elements 1',
            'Intrinsic_safety_current': 'Intrinsic safety current',
            'Intrinsic_safety_inductivity': 'Intrinsic safety inductivity',
            'Intrinsic_safety_capacity': 'Intrinsic safety capacity',
            'Heating_Settings_Antifreeze': 'Heating Settings Antifreeze',
            'Suppl_Char_for_Instr_Elements_2': 'Suppl. Char. for Instr. Elements 2',
            'Intrinsic_safety_voltage': 'Intrinsic safety voltage',
            'Intrinsic_safety_power': 'Intrinsic safety power',
            'Hook_Up_Figure': 'Hook-Up Figure',
            'Variants_in_Parts': 'Variants in Parts',
            'Operating_Pressure_at_Feedback_Location_Maximum': 'Operating Pressure at Feedback Location Maximum',
            'Special_Requirements_': 'Special Requirements',
            "Module_Name": "Module Name",
            "Installation_Site": "Installation Site",
            "Position": "Position",
            "Intrinsic_Safety_Device_Type": "Intrinsic Safety Device Type",
            "Sample_Sensor": "Sample Sensor",
            "Sample_Pipeline_Length": "Sample Pipeline Length",
            "Valve_Number": "Valve Number",
            "Opening_Closing_Times": "Opening/Closing Times",
            "Manufacturer": "Manufacturer",
            "Item_Designation_Block_Default": "Item Designation Block Default",
            "Run_Out_Length": "Run-Out Length",
            "Heating_Limiter": "Heating Limiter",
            "Heating_Remark": "Heating Remark",
            "Comment": "Comment",
            "Overall_Length": "Overall Length",
            "dp_Armature_Characteristic_XT": "dp Armature Characteristic XT",
            "Number_of_Switching_Contacts": "Number of Switching Contacts",
            "Zero_Elevation": "Zero Elevation",
            "Differential_Pressure_Range": "Differential Pressure Range",
            "Restriction_Orifice_Diameter": "Restriction Orifice Diameter",
            "Metering_Cone_Length": "Metering Cone Length",
            "Minimum_Design_Temperature": "Minimum Design Temperature",
            "Valve_Sizing_Factor_b": "Valve Sizing Factor b",
            "Required_Inlet_Length": "Required Inlet Length",
            "Red_Marking_Setting": "Red Marking Setting",
            "Control_Cable_Length_Heating": "Control Cable Length Heating",
            "Capillary_Length": "Capillary Length",
            "Pressure_Recover_Factor_FL": "Pressure Recover Factor FL",
            "Designation": "Designation",
            "Cable_Length_System": "Cable Length System",
            "Quarter_Circle_Nozzle_Radius_r": "Quarter Circle Nozzle Radius r",
            "Theoretical_Ratio_Kvs_Kvo": "Theoretical Ratio Kvs/Kvo",
            "Solenoid_Valve_Design": "Solenoid Valve Design",
            "Sample_Probe_Delay_Time": "Sample Probe Delay Time",
            "Sample_Preparation_Retention_Time": "Sample Preparation Retention Time",
            "Sample_Preparation_Output_Pressure_Normal": "Sample Preparation Output Pressure Normal",
            "Sample_Preparation_Output_Pressure_Maximum": "Sample Preparation Output Pressure Maximum",
            "Sample_Pipeline_Diameter": "Sample Pipeline Diameter",
            "Bypass_Amount_Minimum": "Bypass Amount Minimum",
            "Bypass_Amount_Maximum": "Bypass Amount Maximum",
            "Analyzer_Range_of_Temperature_Compensation": "Analyzer Range of Temperature Compensation",
            "Analyzer_Error_Tolerance": "Analyzer Error Tolerance",
            "Calibration_from": "Calibration from",
            "PA_Bus_max_Short_Circuit_Current": "PA Bus max. Short-Circuit Current",
            "PA_Bus_Current_Input": "PA Bus Current Input",
            "Characteristic_Noise_Value_Zy": "Characteristic Noise Value Zy",
            "Design_Gauge_Pressure": "Design Gauge Pressure",
            "Stroke_Height": "Stroke/Height",
            "Effect_of_dp": "Effect of dp",
            "Voltage": "Voltage",
            "Power_Consumption": "Power Consumption",
            "Measuring_Range_from": "Measuring Range from",
            "Leakage_Rate_of_Kvs": "Leakage Rate (% of Kvs)",
            "Installation_Length": "Installation Length",
            "Kv_Value_at_Kvs_Nominal_Stroke": "Kv Value at Kvs Nominal Stroke",
            "Measuring_Procedure": "Measuring Procedure",
            "Calculated_Maximum_Sound_Pressure_Level": "Calculated Maximum Sound Pressure Level",
            "Final_Acceptances": "Final Acceptances",
            "Output_Speed": "Output Speed",
            "Restrictor_Design": "Restrictor Design",
            "Seat_Diameter": "Seat Diameter",
            "Insert_Length": "Insert Length",
            "Ring_Chamber_Dimension_D": "Ring Chamber Dimension D",
            "Control_Device_Design": "Control Device Design",
            "Control_Valve_Certification": "Control Valve Certification",
            "Kvs_Value": "Kvs-Value",
            "Measuring_Range_to": "Measuring Range to",
            "Overall_Height": "Overall Height",
            "Control_Input_Range": "Control Input Range",
            "Calculated_Kv_Value": "Calculated Kv-Value",
            "Aperture_Diameter_d": "Aperture Diameter d",
            "Calibration_to": "Calibration to",
            "Type_of_Drive": "Type of Drive",
            "Fail_Safe": "Fail Safe",
            "EX_i": "EX (i)",
            "Transfer_to_SAP": "Transfer to SAP",
            "Circuit_Type_Output": "Circuit Type",
            "Power_Supply_from_Module": "Power Supply from Module",
            "Classification": "Classification",
            "Signal_range_resistance": "Signal range/resistance",
            "Method_of_Connection": "Method of Connection",
            "Signal_range": "Signal range",
            "Signal_Voltage_Input": "Signal Voltage Input",
            "Voltage_type": "Voltage type",
            "Classification_by": "Classification by",
            "Edge_change": "Edge change",
            "Signal_Voltage_Output": "Signal Voltage Output",
            "Accuracy_Speed_Output": "Accuracy Speed Output ±",
            "Actuating_Time": "Actuating Time",
            "Actuator_Installation_Position": "Actuator Installation Position",
            "Analyzer_Calibration_Curve": "Analyzer Calibration Curve",
            "Analyzer_90_time_or_Length_of_Analysis": "Analyzer 90 Percentage time or Length of Analysis",
            "Aperture_Angle_Venturi_Tube": "Aperture Angle Venturi Tube",
            "Assembly_Category": "Assembly Category",
            "Assembly_Identifier": "Assembly Identifier",
            "Assembly_Location": "Assembly Location",
            "Auxiliary_Materials": "Auxiliary Materials",
            "Average_Annual_Temperature": "Average Annual Temperature",
            "Bluff_Body_Form": "Bluff Body Form",
            "Breakdown_Torque_Ratio_MK_MN": "Breakdown Torque Ratio MK Per MN",
            "PTB_Number": "PTB Number",
            "Characteristic_Line": "Characteristic Line",
            "Length_Connection_Cable": "Length Connection Cable",
            "Construction_Year": "Construction Year",
            "Control_Cable_Maximum_Number_of_Cable_Inlets": "Control Cable Maximum Number of Cable Inlets",
            "Control_Cable_Maximum_Wire_Cross_Section": "Control Cable Maximum Wire Cross Section",
            "Controllers_Maximum_Number_of_Cable_Inlets": "Controllers Maximum Number of Cable Inlets",
            "Controllers_Maximum_Wire_Cross_Section": "Controllers Maximum Wire Cross Section",
            "Control_Tripping_Voltage": "Control Tripping Voltage",
            "Controller_Maximum": "Controller Maximum",
            "Controller_Minimum": "Controller Minimum",
            "Counter": "Counter",
            "DN": "DN",
            "Cut_Out_Torque": "Cut Out Torque",
            "Density_at_15C": "Density at 15C",
            "Detonation_Hazard_Protection_Type_Heater": "Detonation Hazard Protection Type Heater",
            "Detonation_Hazard_Protection_Type_Motor": "Detonation Hazard Protection Type Motor",
            "Rated_Current_of_Drive": "Rated Current of Drive",
            "Rated_Power_of_Drive": "Rated Power of Drive",
            "Drive_System_for": "Drive System for",
            "Efficiency_at_Nominal_Load": "Efficiency at Nominal Load",
            "Efficiency_at_Nominal_Power_and_Minimum_Rotational_Speed": "Efficiency at Nominal Power and Minimum Rotational Speed",
            "Efficiency_at_Nominal_Power_and_Nominal_Rotational_Speed": "Efficiency at Nominal Power and Nominal Rotational Speed",
            "Engine_Identification_Number": "Engine Identification Number",
            "Default_Component_Name": "Default Component Name",
            "Float_Type_Form": "Float Type Form",
            "Frame_Size": "Frame Size",
            "Default_Symbol_Library": "Default Symbol Library",
            "Default_Symbol": "Default Symbol",
            "Heating_Bundle_Diameter": "Heating Bundle Diameter",
            "Impulse_Factor": "Impulse Factor",
            "Instrument_Layout": "Instrument Layout",
            "Instrument_Layout_Page_Number": "Instrument Layout Page Number",
            "Interrupting_Current_Limit_xIn": "Interrupting Current Limit xIn",
            "Length_of_Displacer": "Length of Displacer",
            "Length_of_Suspension_Device": "Length of Suspension Device",
            "Length_of_Trace_Heating": "Length of Trace Heating",
            "ON_State_Limit_Value_1": "ON State Limit Value 1",
            "ON_State_Limit_Value_2": "ON State Limit Value 2",
            "Limiter_Release": "Limiter Release",
            "Setting_Range_Maximum": "Setting Range Maximum",
            "Setting_Range_Minimum": "Setting Range Minimum",
            "Suppl_char_3_for_loop_elements": "Suppl char 3 for loop elements",
            "Sample_Type": "Sample Type",
            "Maximum_Cable_Length_of_Converter_Motor": "Maximum Cable Length of Converter Motor",
            "Maximum_Coolant_Requirements_at_Nominal_Load": "Maximum Coolant Requirements at Nominal Load",
            "Flow_Maximum": "Flow Maximum",
            "Maximum_Motor_Power_in_Converter_Operation": "Maximum Motor Power in Converter Operation",
            "Maximum_Number_of_Cable_Inlets": "Maximum Number of Cable Inlets",
            "Maximum_Power_Loss": "Maximum Power Loss",
            "Maximum_Rated_Motor_Current": "Maximum Rated Motor Current",
            "Maximum_Rated_Motor_Voltage": "Maximum Rated Motor Voltage",
            "Maximum_Permissible_Sound_Pressure_Level": "Maximum Permissible Sound Pressure Level",
            "Maximum_Wire_Cross_Section": "Maximum Wire Cross Section",
            "Measuring_Range": "Measuring Range",
            "Flow_Minimum": "Flow Minimum",
            "Minimum_Amount_for_Sale": "Minimum Amount for Sale",
            "Motor_Protection_in_Converter_Operation": "Motor Protection in Converter Operation",
            "Motor_Protection_in_Network_Operation": "Motor Protection in Network Operation",
            "Network_Protection": "Network Protection",
            "Noise_Protection_Measures": "Noise Protection Measures",
            "Nominal_Power": "Nominal Power",
            "Nominal_Torque": "Nominal Torque",
            "Maximum_of_Harmonic_Voltage": "Maximum of Harmonic Voltage",
            "nth_Time": "nth Time",
            "Occupation_Density": "Occupation Density",
            "Operating_Pressure_at_Feedback_Location_Normal": "Operating Pressure at Feedback Location Normal",
            "Output_Frequency_Control_Range_from": "Output Frequency Control Range from",
            "Output_Frequency_Control_Range_to": "Output Frequency Control Range to",
            "output_positioner_": "Output Signal",
            "Power_Cable_Maximum_Number_of_Cable_Inlet": "Power Cable Maximum Number of Cable Inlet",
            "Power_Cable_Maximum_Wire_Cross_Section": "Power Cable Maximum Wire Cross Section",
            "Performance_Factor_at_Full_Load": "Performance Factor at Full Load",
            "For_Pre_Post_Pressure_Oscillation": "For Pre Or Post Pressure Oscillation",
            "Pressure_Level": "Pressure Level",
            "Probe_Length": "Probe Length",
            "probe_length_level": "probe length level",
            "PTC_Thermistor_Temperature_Sensor": "PTC Thermistor Temperature Sensor",
            "Pulse_Number_Input_Line_Side_GR": "Pulse Number Input Line Side GR",
            "Pulse_Number_Output_to_Motor_WR": "Pulse Number Output to Motor WR",
            "Radio_Interference_Level": "Radio Interference Level",
            "Rated_Apparent_Power": "Rated Apparent Power",
            "Rated_Current": "Rated Current",
            "Rated_Power": "Rated Power",
            "Rated_Power_at_Nominal_Operation": "Rated Power at Nominal Operation",
            "Rated_Power_per_Meter": "Rated Power per Meter",
            "Rated_Asynchronous_Speed": "Rated Asynchronous Speed",
            "Rated_Torque_MN": "Rated Torque MN",
            "Reference_Temperature": "Reference Temperature",
            "Ring_Chamber_Dimension_A": "Ring Chamber Dimension A",
            "Ring_Chamber_Dimension_E": "Ring Chamber Dimension E",
            "Rotational_Speed_of_Drive": "Rotational Speed of Drive",
            "Rotational_Speed_Range_from": "Rotational Speed Range from",
            "Sample_Pipeline_Type": "Sample Pipeline Type",
            "Sample_Preparation_Back_Pressure_Regulator": "Sample Preparation Back Pressure Regulator",
            "Sample_Preparation_Chemical_Template": "Sample Preparation Chemical Template",
            "Sample_Preparation_Filter": "Sample Preparation Filter",
            "Sample_Preparation_Flow_Counter": "Sample Preparation Flow Counter",
            "Sample_Preparation_Measuring_Product_Cooler": "Sample Preparation Measuring Product Cooler",
            "Sample_Preparation_Miscellaneous": "Sample Preparation Miscellaneous",
            "Sample_Preparation_Reduction_Station": "Sample Preparation Reduction Station",
            "Sample_Preparation_Separator": "Sample Preparation Separator",
            "Sample_Preparation_Tube_Furnace": "Sample Preparation Tube Furnace",
            "Sample_Preparation_Vaporizer": "Sample Preparation Vaporizer",
            "Serial_Number": "Serial Number",
            "Sound_Pressure_Level_at_No_Load": "Sound Pressure Level at No Load",
            "Sound_Pressure_Level_at_Nominal_Load": "Sound Pressure Level at Nominal Load",
            "Special_Paint": "Special Paint",
            "Rotational_Speed_Range_to": "Rotational Speed Range to",
            "Starting_Current_Ratio_IA_IN": "Starting Current Ratio IA Per IN",
            "Starting_Torque_Ratio_MA_MN": "Starting Torque Ratio MA Per MN",
            # "Default_Symbol_Library": "Symbol Library",
            "Symbol_Name": "Symbol Name",
            "TMU": "TMU",
            "Total_Dimensions_Height": "Total Dimensions Height",
            "Total_Dimensions_Length": "Total Dimensions Length",
            "Total_Dimensions_Width": "Total Dimensions Width",
            "Total_Weight": "Total Weight",
            "Total_Weight_of_Motor": "Total Weight of Motor",
            "Travel_Range": "Travel Range",
            "Type_of_Cooling": "Type of Cooling",
            "Weight_for_Choke": "Weight for Choke",
            "Weight_for_Converter": "Weight for Converter",
            "Winding_Circuit": "Winding Circuit",
            "Year_of_Construction": "Year of Construction",
            "Screwed_Joint": "Screwed Joint",
            "Sample_Pipeline_Material": "Sample Pipeline Material",
            "Drive_with_Heating": "Drive with Heating",
            "Bluff_Body_Material": "Bluff Body Material",
            "Seat_Material": "Seat Material",
            "Housing_Material": "Housing Material",
            "Gland_Nut_Lubrication": "Gland Nut Lubrication",
            "Cooling_Fins": "Cooling Fins",
            "Standard_Orifice_Nozzle_Material": "Standard Orifice/Nozzle Material",
            "Tapping_Material": "Tapping Material",
            "Solenoid_Valve": "Solenoid Valve",
            "Function_at_Minimum": "Function at Minimum",
            "Function_at_Maximum": "Function at Maximum",
            "Pressure_Gauge_Shut_Off": "Pressure Gauge Shut-Off",
            "Meter_Metering_Element_Material": "Meter/Metering Element Material",
            "PA_Bus_Terminal": "PA Bus Terminal",
            "Reference_Vessel_Material": "Reference Vessel Material",
            "Head_End_Material": "Head End Material",
            "Short_Circuit_Proof": "Short-Circuit-Proof",
            "Output_Signal_Explosion_Protection": "Output Signal Explosion Protection",
            "Input_Signal_Explosion_Protection": "Input Signal Explosion Protection",
            "FD_Output_Signal": "FD Output Signal",
            "Manual_Actuation": "Manual Actuation",
            "Limit_Switch_sv": "Limit Switch",
            "Wetted_Body_Material": "Wetted Body Material",
            "MT_Head_Assembly": "MT Head Assembly",
            "Spindle_Material": "Spindle Material",
            "Template_Protection_Fluid": "Template Protection Fluid",
            "Restriction_Orifice_Material": "Restriction Orifice Material",
            "Metering_Cone_Material": "Metering Cone Material",
            "Float_Type_Material": "Float-Type Material",
            "Transmitter_Protective_Box": "Transmitter Protective Box",
            "Fine_Adjustment_Valve": "Fine Adjustment Valve",
            "Pump_for_Sample": "Pump for Sample",
            "Pump_for_Sample_Preparation": "Pump for Sample Preparation",
            "Primary_Pressure_Reducer": "Primary Pressure Reducer",
            "Mass_Limitation_before_AGR": "Mass Limitation before AGR",
            "Medium_Connection_Design": "Medium Connection Design",
            "Position_without_Power": "Position without Power",
            "Loop_Diagram_Level": "Loop Diagram Level",
            "Element_type": "Element type",
            "Handwheel_Position": "Handwheel Position",
            "Measured_Quantity": "Measured Quantity",
            "Housing_Type": "Housing Type",
            "Signal_type": "Signal type",
            "Limit_Switch_signaled": "Limit Switch signaled",
            "Digital_Function": "Digital Function",
            "Ring_Chamber_Material": "Ring Chamber Material",
            "characteristic": "characteristic",
            "Auxiliary_power_type": "Auxiliary power type",
            "Flow_Direction": "Flow Direction",
            "Spindle_Bushing": "Spindle Bushing",
            "Resistance_Thermocouple_Type": "Resistance Thermocouple Type",
            "Thermometer_Design": "Thermometer Design",
            "Extension": "Extension",
            "Stelliting": "Stelliting",
            "Thermocouple": "Thermocouple",
            "Housing_Pressure_Stage": "Housing Pressure Stage",
            "Gland_Nut_Type": "Gland Nut Type",
            "Input_Signal": "Input Signal",
            "Galvanic_Separation": "Galvanic Separation",
            "Effective_Direction": "Effective Direction",
            "Cone_Type": "Cone Type",
            "Electrical_Connection_Design": "Electrical Connection Design",
            "Element_fracture": "Element fracture",
            "Seat_Sealing": "Seat Sealing",
            "Gland_Nut_Material": "Gland Nut Material",
            "Auxiliary_Power_Size": "Auxiliary Power Size",
            "Cone_Material": "Cone Material",
            "Switch_State_at_Required_End_Position": "Switch State at Required End Position",
            "Contact_design": "Contact design",
            "Orifice_Filling_medium": "Orifice Filling medium",
            "Counter_Type": "Counter Type",
            "Counter_Design": "Counter Design",
            "Control_Cable_Heating": "Control Cable Heating",
            "Signal_direction": "Signal direction",
            "Scale_Classification": "Scale Classification",
            "Meter_Type": "Meter Type",
            "Display_type": "Display type",
            "Heating": "Heating",
            "Filling_Medium_for_Attenuation": "Filling Medium for Attenuation",
            "Bypass_for_Motor_Network_Operation": "Bypass for Motor Network Operation",
            "Capillary_Liquid": "Capillary Liquid",
            "characteristic_positioner": "characteristic positioner",
            "Circuit_Arrangement": "Circuit Arrangement",
            "Control_Cable_Srewed_Joint": "Control Cable Srewed Joint",
            "Detection_Type": "Detection Type",
            "Device_Type_Machine_Monitoring": "Device Type Machine Monitoring",
            "Enclosure_Type_Class": "Enclosure Type Class",
            "External_Setpoint_Specification": "External Setpoint Specification",
            "Filter_for_Harmonic_Currents": "Filter for Harmonic Currents",
            "Flash_Signaling": "Flash Signaling",
            "Heat_Generator_Installation_Position": "Heat Generator Installation Position",
            "Installation_Layer": "Installation Layer",
            "Insulation_Class": "Insulation Class",
            "Limit_Switch_Close": "Limit Switch Close",
            "Limit_Switch_Open": "Limit Switch Open",
            "Method_of_Measurement_Machine_Monitoring": "Method of Measurement Machine Monitoring",
            "Machine_Type": "Machine Type",
            "Manual_Operation": "Manual Operation",
            "Measured_Value_Display": "Measured Value Display",
            "Design": "Design",
            "Position_Feedback_Analog": "Position Feedback Analog",
            "Power_Cable_Screwed_Joint": "Power Cable Screwed Joint",
            "Red_Marking_Design": "Red Marking Design",
            "Self_Retaining_Drive": "Self-Retaining Drive",
            "Tandem_Switch": "Tandem Switch",
            "Temperature_Controller": "Temperature Controller",
            "Temperature_Limiter": "Temperature Limiter",
            "Terminal_Box_Position_to_drive_end_of_motor": "Terminal Box Position (to drive end of motor)",
            "Circuit_Arrangement2": "Circuit Arrangement2",
            "Torque_Dependent": "Torque Dependent",
            "Torque_Limit_Switch_Close": "Torque Limit Switch Close",
            "Torque_Limit_Switch_Open": "Torque Limit Switch Open",
            "Type_of_Starting": "Type of Starting",
        }

    # Note: added by hand because GPT-4 didn't generate the column filtering
    columns_to_keep = \
        [
            'ClassName',
            'LoopNo',
            'LoopFunc',
            'LService1',
            'Remarks',
            'Status',
            'AreaPath',
            'Size',
            'PIDNo',
            'TagNo',
            'FormatName',
            'Area',
            'Function',
            'Number',
            'suffix',
            'Device_Type',
            'OperatingPrinc',
            'DCSIO',
            'LoopDwgCode',
            'ProcessEquipment',
            'ProcessLines',
            'ISALocation',
            'Ex-ID',
            'Certificate',
            'Parts Code',
            'Facility Block Default',
            'Location Block Def.',
            'description',
            'Model',
            'Suppl. Char. for Instr. Elements 1',
            'Intrinsic safety current',
            'Intrinsic safety inductivity',
            'Intrinsic safety capacity',
            'Heating Settings Antifreeze',
            'Suppl. Char. for Instr. Elements 2',
            'Intrinsic safety voltage',
            'Intrinsic safety power',
            'Hook-Up Figure',
            'Variants in Parts',
            'Operating Pressure at Feedback Location Maximum',
            'Special Requirements',
            'Module Name',
            'Installation Site',
            'Position',
            'Intrinsic Safety Device Type',
            'Sample Sensor',
            'Sample Pipeline Length',
            'Valve Number',
            'Opening/Closing Times',
            'Manufacturer',
            'Item Designation Block Default',
            'Run-Out Length',
            'Heating Limiter',
            'Heating Remark',
            'Comment',
            'Overall Length',
            'dp Armature Characteristic XT',
            'Number of Switching Contacts',
            'Zero Elevation',
            'Differential Pressure Range',
            'Restriction Orifice Diameter',
            'Metering Cone Length',
            'Minimum Design Temperature',
            'Valve Sizing Factor b',
            'Required Inlet Length',
            'Red Marking Setting',
            'Control Cable Length Heating',
            'Capillary Length',
            'Pressure Recover Factor FL',
            'Designation',
            'Cable Length System',
            'Quarter Circle Nozzle Radius r',
            'Theoretical Ratio Kvs/Kvo',
            'Solenoid Valve Design',
            'Sample Probe Delay Time',
            'Sample Preparation Retention Time',
            'Sample Preparation Output Pressure Normal',
            'Sample Preparation Output Pressure Maximum',
            'Sample Pipeline Diameter',
            'Bypass Amount Minimum',
            'Bypass Amount Maximum',
            'Analyzer Range of Temperature Compensation',
            'Analyzer Error Tolerance',
            'Calibration from',
            'PA Bus max. Short-Circuit Current',
            'PA Bus Current Input',
            'Characteristic Noise Value Zy',
            'Design Gauge Pressure',
            'Stroke/Height',
            'Effect of dp',
            'Voltage',
            'Power Consumption',
            'Measuring Range from',
            'Leakage Rate (% of Kvs)',
            'Installation Length',
            'Kv Value at Kvs Nominal Stroke',
            'Measuring Procedure',
            'Calculated Maximum Sound Pressure Level',
            'Final Acceptances',
            'Output Speed',
            'Restrictor Design',
            'Seat Diameter',
            'Insert Length',
            'Ring Chamber Dimension D',
            'Control Device Design',
            'Control Valve Certification',
            'Kvs-Value',
            'Measuring Range to',
            'Overall Height',
            'Control Input Range',
            'Calculated Kv-Value',
            'Aperture Diameter d',
            'Calibration to',
            'Type of Drive',
            'Fail Safe',
            'EX (i)',
            'Transfer to SAP',
            'Circuit Type',
            'Power Supply from Module',
            'Classification',
            'Signal range/resistance',
            'Method of Connection',
            'Signal range',
            'Signal Voltage Input',
            'Voltage type',
            'Classification by',
            'Edge change',
            'Signal Voltage Output',
            'Accuracy Speed Output ±',
            'Actuating Time',
            'Actuator Installation Position',
            'Analyzer Calibration Curve',
            'Analyzer 90 Percentage time or Length of Analysis',
            'Aperture Angle Venturi Tube',
            'Assembly Category',
            'Assembly Identifier',
            'Assembly Location',
            'Auxiliary Materials',
            'Average Annual Temperature',
            'Bluff Body Form',
            'Breakdown Torque Ratio MK Per MN',
            'PTB Number',
            'Characteristic Line',
            'Length Connection Cable',
            'Construction Year',
            'Control Cable Maximum Number of Cable Inlets',
            'Control Cable Maximum Wire Cross Section',
            'Controllers Maximum Number of Cable Inlets',
            'Controllers Maximum Wire Cross Section',
            'Control Tripping Voltage',
            'Controller Maximum',
            'Controller Minimum',
            'Counter',
            'DN',
            'Cut Out Torque',
            'Density at 15C',
            'Detonation Hazard Protection Type Heater',
            'Detonation Hazard Protection Type Motor',
            'Rated Current of Drive',
            'Rated Power of Drive',
            'Drive System for',
            'Efficiency at Nominal Load',
            'Efficiency at Nominal Power and Minimum Rotational Speed',
            'Efficiency at Nominal Power and Nominal Rotational Speed',
            'Engine Identification Number',
            'Default Component Name',
            'Float Type Form',
            'Frame Size',
            'Default Symbol Library',
            'Default Symbol',
            'Heating Bundle Diameter',
            'Impulse Factor',
            'Instrument Layout',
            'Instrument Layout Page Number',
            'Interrupting Current Limit xIn',
            'Length of Displacer',
            'Length of Suspension Device',
            'Length of Trace Heating',
            'ON State Limit Value 1',
            'ON State Limit Value 2',
            'Limiter Release',
            'Setting Range Maximum',
            'Setting Range Minimum',
            'Suppl char 3 for loop elements',
            'Sample Type',
            'Maximum Cable Length of Converter Motor',
            'Maximum Coolant Requirements at Nominal Load',
            'Flow Maximum',
            'Maximum Motor Power in Converter Operation',
            'Maximum Number of Cable Inlets',
            'Maximum Power Loss',
            'Maximum Rated Motor Current',
            'Maximum Rated Motor Voltage',
            'Maximum Permissible Sound Pressure Level',
            'Maximum Wire Cross Section',
            'Measuring Range',
            'Flow Minimum',
            'Minimum Amount for Sale',
            'Motor Protection in Converter Operation',
            'Motor Protection in Network Operation',
            'Network Protection',
            'Noise Protection Measures',
            'Nominal Power',
            'Nominal Torque',
            'Maximum of Harmonic Voltage',
            'nth Time',
            'Occupation Density',
            'Operating Pressure at Feedback Location Normal',
            'Output Frequency Control Range from',
            'Output Frequency Control Range to',
            'Output Signal',
            'Power Cable Maximum Number of Cable Inlet',
            'Power Cable Maximum Wire Cross Section',
            'Performance Factor at Full Load',
            'For Pre Or Post Pressure Oscillation',
            'Pressure Level',
            'Probe Length',
            'probe length level',
            'PTC Thermistor Temperature Sensor',
            'Pulse Number Input Line Side GR',
            'Pulse Number Output to Motor WR',
            'Radio Interference Level',
            'Rated Apparent Power',
            'Rated Current',
            'Rated Power',
            'Rated Power at Nominal Operation',
            'Rated Power per Meter',
            'Rated Asynchronous Speed',
            'Rated Torque MN',
            'Reference Temperature',
            'Ring Chamber Dimension A',
            'Ring Chamber Dimension E',
            'Rotational Speed of Drive',
            'Rotational Speed Range from',
            'Sample Pipeline Type',
            'Sample Preparation Back Pressure Regulator',
            'Sample Preparation Chemical Template',
            'Sample Preparation Filter',
            'Sample Preparation Flow Counter',
            'Sample Preparation Measuring Product Cooler',
            'Sample Preparation Miscellaneous',
            'Sample Preparation Reduction Station',
            'Sample Preparation Separator',
            'Sample Preparation Tube Furnace',
            'Sample Preparation Vaporizer',
            'Serial Number',
            'Sound Pressure Level at No Load',
            'Sound Pressure Level at Nominal Load',
            'Special Paint',
            'Rotational Speed Range to',
            'Starting Current Ratio IA Per IN',
            'Starting Torque Ratio MA Per MN',
            'Symbol Library',
            'Symbol Name',
            'TMU',
            'Total Dimensions Height',
            'Total Dimensions Length',
            'Total Dimensions Width',
            'Total Weight',
            'Total Weight of Motor',
            'Travel Range',
            'Type of Cooling',
            'Weight for Choke',
            'Weight for Converter',
            'Winding Circuit',
            'Year of Construction',
            'Screwed Joint',
            'Sample Pipeline Material',
            'Drive with Heating',
            'Bluff Body Material',
            'Seat Material',
            'Housing Material',
            'Gland Nut Lubrication',
            'Cooling Fins',
            'Standard Orifice/Nozzle Material',
            'Tapping Material',
            'Solenoid Valve',
            'Function at Minimum',
            'Function at Maximum',
            'Pressure Gauge Shut-Off',
            'Meter/Metering Element Material',
            'PA Bus Terminal',
            'Reference Vessel Material',
            'Head End Material',
            'Short-Circuit-Proof',
            'Output Signal Explosion Protection',
            'Input Signal Explosion Protection', # Note: `Input Signal Explosion Protection` replaced to 'Input Signal Explosion Protection'
            'FD Output Signal',
            'Manual Actuation',
            'Limit Switch',
            'Wetted Body Material',
            'MT Head Assembly',
            'Spindle Material',
            'Template Protection Fluid',
            'Restriction Orifice Material',
            'Metering Cone Material',
            'Float-Type Material',
            'Transmitter Protective Box',
            'Fine Adjustment Valve',
            'Pump for Sample',
            'Pump for Sample Preparation',
            'Primary Pressure Reducer',
            'Mass Limitation before AGR',
            'Medium Connection Design',
            'Position without Power',
            'Loop Diagram Level',
            'Element type',
            'Handwheel Position',
            'Measured Quantity',
            'Housing Type',
            'Signal type',
            'Limit Switch signaled',
            'Digital Function',
            'Ring Chamber Material',
            'characteristic',
            'Auxiliary power type',
            'Flow Direction',
            'Spindle Bushing',
            'Resistance Thermocouple Type',
            'Thermometer Design',
            'Extension',
            'Stelliting',
            'Thermocouple',
            'Housing Pressure Stage',
            'Gland Nut Type',
            'Input Signal',
            'Galvanic Separation',
            'Effective Direction',
            'Cone Type',
            'Electrical Connection Design',
            'Element fracture',
            'Seat Sealing',
            'Gland Nut Material',
            'Auxiliary Power Size',
            'Cone Material',
            'Switch State at Required End Position',
            'Contact design',
            'Orifice Filling medium',
            'Counter Type',
            'Counter Design',
            'Control Cable Heating',
            'Signal direction',
            'Scale Classification',
            'Meter Type',
            'Display type',
            'Heating',
            'Filling Medium for Attenuation',
            'Bypass for Motor Network Operation',
            'Capillary Liquid',
            'characteristic positioner',
            'Circuit Arrangement',
            'Control Cable Srewed Joint',
            'Detection Type',
            'Device Type Machine Monitoring',
            'Enclosure Type Class',
            'External Setpoint Specification',
            'Filter for Harmonic Currents',
            'Flash Signaling',
            'Heat Generator Installation Position',
            'Installation Layer',
            'Insulation Class',
            'Limit Switch Close',
            'Limit Switch Open',
            'Method of Measurement Machine Monitoring',
            'Machine Type',
            'Manual Operation',
            'Measured Value Display',
            'Design',
            'Position Feedback Analog',
            'Power Cable Screwed Joint',
            'Red Marking Design',
            'Self-Retaining Drive',
            'Tandem Switch',
            'Temperature Controller',
            'Temperature Limiter',
            'Terminal Box Position (to drive end of motor)',
            'Circuit Arrangement2',
            'Torque Dependent',
            'Torque Limit Switch Close',
            'Torque Limit Switch Open',
            'Type of Starting',
            'Wiring_Config',
            'junction_box',
            'SpecialRemarks'
        ]

    renamed_dataframe = \
        __rename_columns(
            s_instrument_index,
            column_rename_dict)

    # Note: it was added because the dict of column names cannot have duplicate keys
    #  it has to be fixed - change the storage type
    #  used 'Default Symbol Library' instead of 'Default_Symbol_Library' because the column was previously renamed
    renamed_dataframe['Symbol Library'] = \
        renamed_dataframe['Default Symbol Library']

    # Note: added by hand to filter the set of columns
    renamed_dataframe = \
        renamed_dataframe.filter(
            items=columns_to_keep)

    instrument_index_dataframe = \
        __get_distinct_rows(
            renamed_dataframe)

    return \
        instrument_index_dataframe


def __rename_columns(
        dataframe: pandas.DataFrame,
        column_rename_dict: Dict[str, str]) \
        -> pandas.DataFrame:
    return \
        dataframe.rename(
            columns=column_rename_dict)


def __get_distinct_rows(
        dataframe: pandas.DataFrame) \
        -> pandas.DataFrame:
    return \
        dataframe.drop_duplicates()
