def get_loop_index_mappings_from_model() \
        -> dict:
    # TODO - to be retrieved from model
    return \
        {
            'cs_loop_kat_id': 'function',
            'loop_cs_comment': 'remarks',
            'cs_function_description': 'func_description',
            'sap_responsible_work_center': 'resp_work_center',
            'cs_air_distributor': 'air_distributor',
            'cs_variable_part_drawing_number': 'var_part_of_drawing_no',
            'cs_loop_id_1': 'suppl_char_1',
            'cs_visual_inspection': 'visual_inspection',
            'cs_y_coordinate_pi_data': 'y_coord.',
            'cs_et_node_path': 'et_structure',
            'cs_x_coordinate_pi_data': 'x_coord.',
            'cs_field_distributor_output_id': 'field_distrib_output',
            'cs_loop_id_3': 'suppl_char_3',
            'cs_loop_id_2': 'suppl_char_2',
            'sap_planning_group': 'planning_group',
            'cs_tested_by': 'tested_by',
            'cs_test_acc_to_test_catalog': 'test_acc_to_test_catalog',
            'cs_test_acc_by_test_catalog': 'test_acc_by_test_catalog',
            'cs_logic_diagram_typical': 'logic_diag_typical',
            'cs_inspection_purpose': 'purpose_of_inspection',
            'cs_inspection_interval': 'inspection_interval',
            'loop_cs_loop_unit': 'unit',
            'cs_accompanying_documents': 'accomp_documents',
            'cs_field_distributor_input_id': 'field_distrib_input',
            'cs_realization_position': 'realization_pos',
            'cs_function_test': 'function_test',
            'cs_loop_description_3': 'loop_service_3',
            'cs_graphic_typical': 'graphical_typical',
            'cs_standard_loop_id': 'standard_loop_id',
            'cs_loop_description_2': 'loop_service_2',
            'cs_loop_status_remark': 'status_remark',
            'cs_loop_lfd_nr': 'loop_no',
            'cs_loop_function': 'loop_function',
        }
