from enum import Enum

from nf_common_source.code.nf.types.column_types import ColumnTypes

class SConnection(ColumnTypes):
    FROM_FACILITY = "from_facility"
    FROM_LOCATION = "from_location"
    WIRE_OBJECT_IDENTIFIER = "wire_object_identifier"
    CABLE_OBJECT_IDENTIFIER = "cable_object_identifier"
    TO_ITEM_OBJECT_IDENTIFIER = "to_item_object_identifier"
    FROM_ITEM = "from_item"
    FROM_DYNAMIC_CLASS = "from_dynamic_class"
    TO_CONNECTION_PIN_HREF = "to_connection_pin_href"
    FROM_OBJECT_IDENTIFIER = "from_object_identifier"
    TO_DYNAMIC_CLASS = "to_dynamic_class"
    FROM_ITEM_DYNAMIC_CLASS = "from_item_dynamic_class"
    FROM_ITEM_OBJECT_IDENTIFIER = "from_item_object_identifier"
    TO_OBJECT_IDENTIFIER = "to_object_identifier"
    TO_ITEM_DYNAMIC_CLASS = "to_item_dynamic_class"
    FROM_TERMINAL_MARKING = "from_terminal_marking"
    CABLE = "cable"
    WIRE_CROSS_SECTION = "wire_cross_section"
    WIRE_MARKINGS = "wire_markings"
    TO_LOCATION = "to_location"
    TO_FACILITY = "to_facility"
    TO_ITEM = "to_item"
    TO_TERMINAL_MARKING = "to_terminal_marking"
    LOOP_NUMBER = "loop_number"
    TAG_NUMBER = "tag_number"
    DOCUMENT_NUMBER = "document_number"
    CONNECTION_TYPE = "connection_type"
    PARQUET_FILE_RELATIVE_PATH = "parquet_file_relative_path"
    DATABASE_NAME = "database_name"
    OBJECT_IDENTIFIER = "object_identifier"
    FROM_CONNECTION_PIN_HREF = "from_connection_pin_href"
