from nf_common_source.code.nf.types.column_types import ColumnTypes

class S_DeviceCatalogueColumns(ColumnTypes):
    PARQUET_FILE_RELATIVE_PATH = "parquet_file_relative_path"
    CATALOGUE_RNT = "catalogue_rnt"
    ITEM_DYNAMIC_CLASS = "item_dynamic_class"
    OBJECT_IDENTIFIER = "object_identifier"
    DYNAMIC_CLASS = "dynamic_class"
    ITEM_OBJECT_IDENTIFIER = "item_object_identifier"
    DATABASE_NAME = "database_name"
    PRODUCT_KEY = "product_key"
    TAG_NUMBER = "tag_number"
    DOCUMENT_NUMBER = "document_number"
    LOOP_NUMBER = "loop_number"
    ALLOW_USE = "allowuse"
    TYPE = "type"
    DESCRIPTION = "description"
    MANUFACTURER = "manufacturer"
    MODEL_NO = "modelno"
    CLASS = "class"
    LEFT = "left"
    RIGHT = "right"
    LEFT_MARKING = "left_marking"
    RIGHT_MARKING = "right_marking"
    SYMBOL_NAME = "symbol_name"