
sigraph_dyn_classes= [
     ("LC_Cable_run_pt", "Cable_run_pt",None,None)
    ,("LC_Main_location", "Main_location",None,None)
    ,("LC_Function_el_pin", "LC_Function_el_pin", ["LC_function_pin_rel", "LC_Wire_function_Function_pin_Rel"],None)
    ,("LC_Function_diag_el_pin", "LC_Function_diag_el_pin",None,None)
    ,("LC_Integrated_function", "Integrated_function",None,None)
    ,("LC_PLC_Supply", "PLC_Supply",None,None)
    ,("LC_General_function", "General_function",None,None)
    ,("LC_Terminal_strip", "Terminal_strip",None,None)
    ,("LC_PLC_Module", "PLC_Module",None,None)
    ,("LC_General_item", "General_item",None,None)
    ,("LC_Integrated_item", "Integrated_item",None,None)
    ,("LC_Main_facility", "Main_facility",None,None)
    ,("LC_Sub_location", "Sub_location",None,None)
    ,("LC_Busbar", "Busbar",None,None)
    ,("LC_Function_def", "Function_def",None,None)
    ,("LC_Cable", "Cable",None,None)
    ,("LC_Wire_function", "Wire_function",None,None)
    ,("LC_Cable_overview_function", "Cable_overview_function",None,None)
    ,("LC_Pin_group", "Pin_group",None,None)
    ,("LC_Item_k", "Item_k",None,None)
    ,("LC_Subrack", "Subrack",None,None)
    ,("PLC_Other_system", "PLC_Other_system",None,None)
    ,("LC_Function_br_pin", "br_pin",None,None)
    ,("LC_Function_wire_pin", "wire_pin",None,None)
    ,("DM_Report_document", "DM_Report_document",None,None)
    ,("DM_Circuit_diagram", "DM_Circuit_diagram",None,None)
    ,("DM_Terminal_diagram", "DM_Terminal_diagram",None,None)
    ,("PC_Cable_eq", "Cable_eq",None,None)
    ,("PC_Std_part_def", "Std_part_def",None,None)
    ,("LC_Net", "LC_Net",None,None)
    ,("PC_Part", "PC_Part",None,None)
    ,("LC_PLC_Module", "PLC_Module",None,None)
    ,("PLC_Function_special", "PLC_Function_special",None,None)
    ,("LC_Structured_function", "LC_Structured_function",None,None)
    ,("CS_Loop_subfunction_actuator", "CS_Loop_subfunction_actuator",["CS_Loop_subfunction_act_sen_CS_Loop_element"],None)
    ,("CS_Loop_subfunction_sensor", "CS_Loop_subfunction_sensor",["CS_Loop_subfunction_act_sen_CS_Loop_element"],None)
    ,("CS_Mechanical_data_actuator", "CS_Mechanical_data_actuator", ["CS_Mechanical_data_CS_Loop_element"],None)
    ,("CS_Mechanical_data_sensor", "CS_Mechanical_data_sensor", ["CS_Mechanical_data_CS_Loop_element"],None)
    ,("CS_PI_data", "CS_PI_data", "CS_PI_data_CS_Loop",None,None)
    ,("CS_Pin", 'CS_Pin',None,None)
    ,("CS_Pin_catalogue", "CS_Pin_catalogue",None,None)
    ,("CS_Pipe_class", "CS_Pipe_class",None,None)
    ,("CS_Pipeline_section", "CS_Pipeline_section",None,None)
    ,("CS_Process_data_actuator", "CS_Process_data_actuator", ["CS_Process_data_CS_Loop_element"],None)
    ,("CS_Process_data_sensor", "CS_Process_data_sensor", ["CS_Process_data_CS_Loop_element"],None)
    ,("CS_Process_flow_diagram",  "CS_Process_flow_diagram",None,None)
    ,("CS_Terminal_layer", "CS_Terminal_layer",None,None)
    ,("CS_Terminal_level", 'CS_Terminal_level',None,None)
    ,("CS_Terminal_typical", "CS_Terminal_typical",None,None)
    ,("DM_Cabinet_diagram", "DM_Cabinet_diagram",None,None)
    ,("DM_Document_id", "DM_Document_id",None,None)
    ,("DM_Folder_node_1", 'DM_Folder_node_1',None,None)
    ,("DM_Folder_node_2", 'DM_Folder_node_2',None,None)
    ,("DM_Folder_node_3", 'DM_Folder_node_3',None,None)
    ,("DM_Folder_node_4", 'DM_Folder_node_4',None,None)
    ,("LC_Constructional_unit", 'LC_Constructional_unit',None,None)
    ,("LC_ET200_Terminalblock", 'LC_ET200_Terminalblock',None,None)
    ,("LC_Generalmodule", "LC_Generalmodule",None,None)
    ,("LC_Installation_site",  "LC_Installation_site",None,None)
    ,("LC_Location_type",  "LC_Location_type",None,None)
    ,("LC_Sub_facility",  "Sub_facility",None,None)
    ,("LC_Terminal_group",  "LC_Terminal_group",None,None)
    ,("LC_Installation_site",  "LC_Installation_site",None,None)
    ,("CS_Loop_element_hw_actuator", "CS_Loop_element_hw_actuator",None,None)
    ,("CS_Loop_element_hw_ai",  "CS_Loop_element_hw_ai",None,None)
    ,("CS_Loop_element_hw_ao",  "CS_Loop_element_hw_ao",None,None)
    ,("CS_Loop_element_hw_bi",  "CS_Loop_element_hw_bi",None,None)
    ,("CS_Loop_element_hw_bo",  "CS_Loop_element_hw_bo",None,None)
    ,("CS_Loop_element_hw_control_valve",  "CS_Loop_element_hw_control_valve",None,None)
    ,("CS_Loop_element_hw_density",  "CS_Loop_element_hw_density",None,None)
    ,("CS_Loop_element_hw_dist_len_pos",  "CS_Loop_element_hw_dist_len_pos",None,None)
    ,("CS_Loop_element_hw_flow",  "CS_Loop_element_hw_flow",None,None)
    ,("CS_Loop_element_hw_flow_meter",  "CS_Loop_element_hw_flow_meter",None,None)
    ,("CS_Loop_element_hw_humidity",  "CS_Loop_element_hw_humidity",None,None)
    ,("CS_Loop_element_hw_indication_operating",  "CS_Loop_element_hw_indication_operating",None,None)
    ,("CS_Loop_element_hw_level",  "CS_Loop_element_hw_level",None,None)
    ,("CS_Loop_element_hw_man_feed",  "CS_Loop_element_hw_man_feed",None,None)
    ,("CS_Loop_element_hw_misc",  "CS_Loop_element_hw_misc",None,None)
    ,("CS_Loop_element_hw_pressure",  "CS_Loop_element_hw_pressure",None,None)
    ,("CS_Loop_element_hw_quality",  "CS_Loop_element_hw_quality",None,None)
    ,("CS_Loop_element_hw_radiation",  "CS_Loop_element_hw_radiation",None,None)
    ,("CS_Loop_element_hw_signal_adaptation",  "CS_Loop_element_hw_signal_adaptation",None,None)
    ,("CS_Loop_element_hw_singledevice",  "CS_Loop_element_hw_singledevice",None,None)
    ,("CS_Loop_element_hw_solenoid_valve",  "CS_Loop_element_hw_solenoid_valve",None,None)
    ,("CS_Loop_element_hw_speed",  "CS_Loop_element_hw_speed",None,None)
    ,("CS_Loop_element_hw_temp",  "CS_Loop_element_hw_temp",None,None)
    ,("CS_Loop_element_hw_weight", "CS_Loop_element_hw_weight",None,None)   
]

