from enum import Enum


class LoopFilteredFor11SLoopIndexSql0100Sql(
        Enum):
    CS_ACCOMPANYING_DOCUMENTS = 'cs_accompanying_documents'
    CS_AIR_DISTRIBUTOR = 'cs_air_distributor'
    CS_ET_NODE_PATH = 'cs_et_node_path'
    CS_FIELD_DISTRIBUTOR_INPUT_ID = 'cs_field_distributor_input_id'
    CS_FIELD_DISTRIBUTOR_OUTPUT_ID = 'cs_field_distributor_output_id'
    CS_FUNCTION_DESCRIPTION = 'cs_function_description'
    CS_FUNCTION_TEST = 'cs_function_test'
    CS_GRAPHIC_TYPICAL = 'cs_graphic_typical'
    CS_INSPECTION_INTERVAL = 'cs_inspection_interval'
    CS_INSPECTION_PURPOSE = 'cs_inspection_purpose'
    CS_LOGIC_DIAGRAM_TYPICAL = 'cs_logic_diagram_typical'
    CS_LOOP_DESCRIPTION_1 = 'cs_loop_description_1'
    CS_LOOP_DESCRIPTION_2 = 'cs_loop_description_2'
    CS_LOOP_DESCRIPTION_3 = 'cs_loop_description_3'
    CS_LOOP_FUNCTION = 'cs_loop_function'
    CS_LOOP_ID = 'cs_loop_id'
    CS_LOOP_ID_1 = 'cs_loop_id_1'
    CS_LOOP_ID_2 = 'cs_loop_id_2'
    CS_LOOP_ID_3 = 'cs_loop_id_3'
    CS_LOOP_KAT_ID = 'cs_loop_kat_id'
    CS_LOOP_LFD_NR = 'cs_loop_lfd_nr'
    CS_LOOP_STATUS = 'cs_loop_status'
    CS_LOOP_STATUS_REMARK = 'cs_loop_status_remark'
    CS_REALIZATION_POSITION = 'cs_realization_position'
    CS_RELATED_REPORT = 'cs_related_report'
    CS_ROOT_EXTRACTION_POINT = 'cs_root_extraction_point'
    CS_SIFPRO_RELEVANT = 'cs_sifpro_relevant'
    CS_SOURCE = 'cs_source'
    CS_SPECIAL_REQUIREMENTS_1 = 'cs_special_requirements_1'
    CS_SPECIAL_REQUIREMENTS_2 = 'cs_special_requirements_2'
    CS_SPECIAL_REQUIREMENTS_3 = 'cs_special_requirements_3'
    CS_STANDARD_LOOP_ID = 'cs_standard_loop_id'
    CS_TEST_ACC_BY_TEST_CATALOG = 'cs_test_acc_by_test_catalog'
    CS_TEST_ACC_TO_TEST_CATALOG = 'cs_test_acc_to_test_catalog'
    CS_TESTED_BY = 'cs_tested_by'
    CS_VARIABLE_PART_DRAWING_NUMBER = 'cs_variable_part_drawing_number'
    CS_VISUAL_INSPECTION = 'cs_visual_inspection'
    CS_X_COORDINATE_PI_DATA = 'cs_x_coordinate_pi_data'
    CS_Y_COORDINATE_PI_DATA = 'cs_y_coordinate_pi_data'
    LAYER_CS_LOOP_DYN_CLASS = 'layer_cs_loop_dyn_class'
    LAYER_CS_LOOP_HREF = 'layer_cs_loop_href'
    LOOP_CS_CLASSIFICATION = 'loop_cs_classification'
    LOOP_CS_CLASSIFICATION_BY = 'loop_cs_classification_by'
    LOOP_CS_COMMENT = 'loop_cs_comment'
    LOOP_CS_LOOP_UNIT = 'loop_cs_loop_unit'
    LOOP_DATABASE_NAME = 'loop_database_name'
    LOOP_DYNAMIC_CLASS = 'loop_dynamic_class'
    LOOP_OBJECT_IDENTIFIER = 'loop_object_identifier'
    SAP_PLANNING_GROUP = 'sap_planning_group'
    SAP_RESPONSIBLE_WORK_CENTER = 'sap_responsible_work_center'
