from enum import Enum


class LoopFilteredFor11SLoopIndexSql0100SqlParquet(
        Enum):
    CS_ACCOMPANYING_DOCUMENTS = 'CS_accompanying_documents'
    CS_AIR_DISTRIBUTOR = 'CS_air_distributor'
    CS_ET_NODE_PATH = 'CS_et_node_path'
    CS_FIELD_DISTRIBUTOR_INPUT_ID = 'CS_field_distributor_input_id'
    CS_FIELD_DISTRIBUTOR_OUTPUT_ID = 'CS_field_distributor_output_id'
    CS_FUNCTION_DESCRIPTION = 'CS_function_description'
    CS_FUNCTION_TEST = 'CS_function_test'
    CS_GRAPHIC_TYPICAL = 'CS_graphic_typical'
    CS_INSPECTION_INTERVAL = 'CS_inspection_interval'
    CS_INSPECTION_PURPOSE = 'CS_inspection_purpose'
    CS_LOGIC_DIAGRAM_TYPICAL = 'CS_logic_diagram_typical'
    CS_LOOP_DESCRIPTION_1 = 'CS_loop_description_1'
    CS_LOOP_DESCRIPTION_2 = 'CS_loop_description_2'
    CS_LOOP_DESCRIPTION_3 = 'CS_loop_description_3'
    CS_LOOP_FUNCTION = 'CS_loop_function'
    CS_LOOP_ID = 'CS_loop_id'
    CS_LOOP_ID_1 = 'CS_loop_id_1'
    CS_LOOP_ID_2 = 'CS_loop_id_2'
    CS_LOOP_ID_3 = 'CS_loop_id_3'
    CS_LOOP_KAT_ID = 'CS_loop_kat_id'
    CS_LOOP_LFD_NR = 'CS_loop_lfd_nr'
    CS_LOOP_STATUS = 'CS_loop_status'
    CS_LOOP_STATUS_REMARK = 'CS_loop_status_remark'
    CS_REALIZATION_POSITION = 'CS_realization_position'
    CS_RELATED_REPORT = 'CS_related_report'
    CS_ROOT_EXTRACTION_POINT = 'CS_root_extraction_point'
    CS_SIFPRO_RELEVANT = 'CS_sifpro_relevant'
    CS_SOURCE = 'CS_source'
    CS_SPECIAL_REQUIREMENTS_1 = 'CS_special_requirements_1'
    CS_SPECIAL_REQUIREMENTS_2 = 'CS_special_requirements_2'
    CS_SPECIAL_REQUIREMENTS_3 = 'CS_special_requirements_3'
    CS_STANDARD_LOOP_ID = 'CS_standard_loop_id'
    CS_TEST_ACC_BY_TEST_CATALOG = 'CS_test_acc_by_test_catalog'
    CS_TEST_ACC_TO_TEST_CATALOG = 'CS_test_acc_to_test_catalog'
    CS_TESTED_BY = 'CS_tested_by'
    CS_VARIABLE_PART_DRAWING_NUMBER = 'CS_variable_part_drawing_number'
    CS_VISUAL_INSPECTION = 'CS_visual_inspection'
    CS_X_COORDINATE_PI_DATA = 'CS_x_coordinate_pi_data'
    CS_Y_COORDINATE_PI_DATA = 'CS_y_coordinate_pi_data'
    LAYER_CS_LOOP_DYN_CLASS = 'Layer_CS_Loop_dyn_class'
    LAYER_CS_LOOP_HREF = 'Layer_CS_Loop_href'
    LOOP_CS_CLASSIFICATION = 'loop_CS_classification'
    LOOP_CS_CLASSIFICATION_BY = 'loop_CS_classification_by'
    LOOP_CS_COMMENT = 'loop_CS_comment'
    LOOP_CS_LOOP_UNIT = 'loop_CS_loop_unit'
    LOOP_DATABASE_NAME = 'loop_database_name'
    LOOP_DYNAMIC_CLASS = 'loop_dynamic_class'
    LOOP_OBJECT_IDENTIFIER = 'loop_object_identifier'
    SAP_PLANNING_GROUP = 'SAP_planning_group'
    SAP_RESPONSIBLE_WORK_CENTER = 'SAP_responsible_work_center'

