from enum import Enum


class S_CableSchedule(
        Enum):
    ADAPTER_FROM = 'adapter_from'
    ADAPTER_TO = 'adapter_to'
    BENDING_RADIUS = 'bending_radius'
    BODY_LENGTH = 'body_length'
    CABLE_DRUM_NUMBER = 'cable_drum_number'
    CABLE_SET = 'cable_set'
    CABLENUMBER = 'cablenumber'
    CAPACITANCE_PER_KM = 'capacitance_per_km'
    CATALOGUENO = 'catalogueno'
    COMPONENT_DESCRIPTION_1 = 'component_description_1'
    CONDUCTOR_TYPE = 'conductor_type'
    DATABASE_NAME = 'database_name'
    DISCIPLINE = 'discipline'
    DYNAMIC_CLASS = 'dynamic_class'
    EAN_NUMBER = 'ean_number'
    ESTIMATED_LENGTH = 'estimated_length'
    EXTERNAL_DOCUMENT_OF_ITEM = 'external_document_of_item'
    FROM_LOCATION = 'from_location'
    FUNCTION_TEXT_1 = 'function_text_1'
    GLAND_FROM = 'gland_from'
    GLAND_TO = 'gland_to'
    INDUCTANCE_PER_KM = 'inductance_per_km'
    INSTALLATION_DATE = 'installation_date'
    INSTALLED_LENGTH = 'installed_length'
    INSULATING_MATERIAL = 'insulating_material'
    LAYING_CORNER_POINT = 'laying_corner_point'
    LENGTH = 'length'
    LEVEL_OF_INSTALLATION = 'level_of_installation'
    LIST_PRICE = 'list_price'
    MASS = 'mass'
    MAX_AMBIENT_TEMPERATURE = 'max_ambient_temperature'
    MEASURE_UNIT_QUALIFIER = 'measure_unit_qualifier'
    MIN_AMBIENT_TEMPERATURE = 'min_ambient_temperature'
    MOUNTING_FEATURE = 'mounting_feature'
    OBJECT_IDENTIFIER = 'object_identifier'
    OUTSIDE_DIAMETER = 'outside_diameter'
    PRECIOUS_METAL_FACTOR_1 = 'precious_metal_factor_1'
    PRECIOUS_METAL_FACTOR_2 = 'precious_metal_factor_2'
    PROJECTSTATUS = 'projectstatus'
    QUANTITY_UNIT = 'quantity_unit'
    RANGE = 'range'
    RATED_TEMPERATURE = 'rated_temperature'
    RATED_VOLTAGE_U = 'rated_voltage_u'
    RATED_VOLTAGE_UO = 'rated_voltage_uo'
    REMARKS = 'remarks'
    SELECTION_KEY = 'selection_key'
    SHIELD = 'shield'
    SHIELD_NUMBER = 'shield_number'
    SUBASSEMBLY_INFORMATION = 'subassembly_information'
    SUPPLIERS_ARTICLE_NO = 'suppliers_article_no'
    TO_LOCATION = 'to_location'
    WIRE_NUMBER = 'wire_number'
    WIRE_TYPE = 'wire_type'
