from enum import Enum


class S_Connection(
        Enum):
    CABLE = 'cable'
    CABLE_OBJECT_IDENTIFIER = 'cable_object_identifier'
    CONNECTION_TYPE = 'connection_type'
    DATABASE_NAME = 'database_name'
    DOCUMENT_NUMBER = 'document_number'
    FROM_CONNECTION_PIN_HREF = 'from_connection_pin_href'
    FROM_DYNAMIC_CLASS = 'from_dynamic_class'
    FROM_FACILITY = 'from_facility'
    FROM_ITEM = 'from_item'
    FROM_ITEM_DYNAMIC_CLASS = 'from_item_dynamic_class'
    FROM_ITEM_OBJECT_IDENTIFIER = 'from_item_object_identifier'
    FROM_LOCATION = 'from_location'
    FROM_OBJECT_IDENTIFIER = 'from_object_identifier'
    FROM_TERMINAL_MARKING = 'from_terminal_marking'
    LOOP_NUMBER = 'loop_number'
    OBJECT_IDENTIFIER = 'object_identifier'
    TAG_NUMBER = 'tag_number'
    TO_CONNECTION_PIN_HREF = 'to_connection_pin_href'
    TO_DYNAMIC_CLASS = 'to_dynamic_class'
    TO_FACILITY = 'to_facility'
    TO_ITEM = 'to_item'
    TO_ITEM_DYNAMIC_CLASS = 'to_item_dynamic_class'
    TO_ITEM_OBJECT_IDENTIFIER = 'to_item_object_identifier'
    TO_LOCATION = 'to_location'
    TO_OBJECT_IDENTIFIER = 'to_object_identifier'
    TO_TERMINAL_MARKING = 'to_terminal_marking'
    WIRE_CROSS_SECTION = 'wire_cross_section'
    WIRE_MARKINGS = 'wire_markings'
    WIRE_OBJECT_IDENTIFIER = 'wire_object_identifier'
