from enum import Enum


class Cable_Schedule(
        Enum):
    CATALOGUENO = 'catalogueno'
    REMARKS = 'remarks'
    CABLENUMBER = 'cablenumber'
    FROM_LOCATION = 'from_location'
    TO_LOCATION = 'to_location'
    LENGTH = 'length'
    PROJECTSTATUS = 'projectstatus'
    GLAND_FROM = 'gland_from'
    GLAND_TO = 'gland_to'
    ADAPTER_FROM = 'adapter_from'
    ADAPTER_TO = 'adapter_to'
    RANGE = 'range'
    CABLE_DRUM_NUMBER = 'cable drum number'
    LAYING_CORNER_POINT = 'laying corner point'
    EXTERNAL_DOCUMENT_OF_ITEM = 'external document of item'
    INSTALLED_LENGTH = 'installed length'
    INSTALLATION_DATE = 'installation date'
    ESTIMATED_LENGTH = 'estimated length'
    FUNCTION_TEXT_1 = 'function text 1'
    LEVEL_OF_INSTALLATION = 'level of installation'
    SHIELD_NUMBER = 'shield number'
    WIRE_NUMBER = 'wire number'
    CABLE_SET = 'cable set'
    WIRE_TYPE = 'wire type'
    CONDUCTOR_TYPE = 'conductor type'
    INSULATING_MATERIAL = 'insulating material'
    INDUCTANCE_PER_KM = 'inductance per km'
    BENDING_RADIUS = 'bending radius'
    CAPACITANCE_PER_KM = 'capacitance per km'
    SHIELD = 'shield'
    RATED_VOLTAGE_UO = 'rated_voltage uo'
    RATED_VOLTAGE_U = 'rated_voltage u'
    PRECIOUS_METAL_FACTOR_2 = 'precious metal factor 2'
    PRECIOUS_METAL_FACTOR_1 = 'precious metal factor 1'
    SUPPLIERS_ARTICLE_NUMBER = 'suppliers article number'
    MASS = 'mass'
    COMPONENT_DESCRIPTION_1 = 'component description 1'
    SELECTION_KEY = 'selection key'
    OUTSIDE_DIAMETER = 'outside diameter'
    SUBASSEMBLY_INFORMATION = 'subassembly information'
    RATED_TEMPERATURE = 'rated temperature'
    QUANTITY_UNIT = 'quantity unit'
    MOUNTING_FEATURE = 'mounting feature'
    MINIMUM_AMBIENT_TEMPERATURE = 'minimum ambient temperature'
    MEASURE_UNIT_QUALIFIER = 'measure unit qualifier'
    MAXIMUM_AMBIENT_TEMPERATURE = 'maximum ambient temperature'
    LIST_PRICE = 'list price'
    EAN_NUMBER = 'ean number'
    BODY_LENGTH = 'body length'
