from enum import Enum


class Loop_Index(
        Enum):
    ACCOMP_DOCUMENTS = 'accomp documents'
    AIR_DISTRIBUTOR = 'air distributor'
    AREA = 'area'
    AREAPATH = 'areapath'
    CLASSIFICATION = 'classification'
    CLASSIFICATION_BY = 'classification by'
    CLASSNAME = 'classname'
    DRAWING = 'drawing'
    EP_ORIGIN = 'ep origin'
    ET_STRUCTURE = 'et structure'
    FIELD_DISTRIB_INPUT = 'field distrib input'
    FIELD_DISTRIB_OUTPUT = 'field distrib output'
    FORMATNAME = 'formatname'
    FUNC_DESCRIPTION = 'func description'
    FUNCTION = 'function'
    FUNCTION_TEST = 'function test'
    GRAPHICAL_TYPICAL = 'graphical typical'
    INSPECTION_INTERVAL = 'inspection interval'
    LOGIC_DIAG_TYPICAL = 'logic diag typical'
    LOOP_FUNCTION = 'loop function'
    LOOP_NO = 'loop no'
    LOOP_SERVICE_1 = 'loop service-1'
    LOOP_SERVICE_2 = 'loop service-2'
    LOOP_SERVICE_3 = 'loop service-3'
    NUMBER = 'number'
    PLANNING_GROUP = 'planning group'
    PURPOSE_OF_INSPECTION = 'purpose of inspection'
    REALIZATION_POS = 'realization pos'
    RELATED_REPORT = 'related report'
    REMARKS = 'remarks'
    RESP_WORK_CENTER = 'resp work center'
    ROOT_EXTRACTION_POINT = 'root extraction point'
    SIFPRO_RELEVANT = 'sifpro relevant'
    SPECIAL_REQ_1 = 'special req 1'
    SPECIAL_REQ_2 = 'special req 2'
    SPECIAL_REQ_3 = 'special req 3'
    STANDARD_LOOP_ID = 'standard loop id'
    STATUS = 'status'
    STATUS_REMARK = 'status remark'
    SUFFIX = 'suffix'
    SUPPL_CHAR_1 = 'suppl char 1'
    SUPPL_CHAR_2 = 'suppl char 2'
    SUPPL_CHAR_3 = 'suppl char 3'
    TEST_ACC_BY_TEST_CATALOG = 'test acc by test catalog'
    TEST_ACC_TO_TEST_CATALOG = 'test acc to test catalog'
    TESTED_BY = 'tested by'
    UNIT = 'unit'
    VAR_PART_OF_DRAWING_NO = 'var part of drawing no'
    VISUAL_INSPECTION = 'visual inspection'
    WIRED = 'wired'
    X_COORD = 'x coord.'
    Y_COORD = 'y coord.'
